FROM rust:latest AS dev

WORKDIR /app

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml ./
RUN cargo fetch

COPY src ./src
COPY proto ./proto
COPY build.rs ./

CMD ["cargo", "watch", "-x", "run"]