services:
  db:
    image: postgres
    container_name: tracking-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=tracking
  java-service:
    container_name: java-service
    depends_on:
      - db
    build:
      context: ./docker/java-service
      dockerfile: Dockerfile.dev
    environment:
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
      - SPRING_PROFILE_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tracking-db:5432/tracking
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    stdin_open: true
    tty: true
    volumes:
      - ./docker/java-service:/app
      - ~/.m2:/root/.m2
      - ./docker/scripts:/usr/local/bin
    ports:
      - "8080:8080"
      - "9090:9090"
      - "5005:5005"
  rust-service:
    build:
      context: ./docker/rust-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./docker/rust-service:/app
      - ~/.cargo/registry:/usr/local/cargo/registry
      - ~/.cargo/git:/usr/local/cargo/git
      - ./docker/rust-service/target:/app/target
  go-service:
    depends_on:
      - java-service
    build:
      context: ./docker/go-service
      dockerfile: Dockerfile.dev
    command: ["/bin/bash", "-c", "/usr/local/bin/wait-for-it.sh java-service/9090 -- /go-service -cron '*/1 * * * *' -addr 'java-service:9090'"]
    volumes:
      - ./docker/go-service:/app
      - ~/.cache/go:/root/.cache/go
      - ./docker/scripts:/usr/local/bin