version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tracking-db
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=tracking
  backend:
    container_name: backend-api
    depends_on:
      - db
    build:
      context: ./backend-api
      dockerfile: DockerfileProd
    environment:
      - SPRING_PROFILE_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tracking-db:5432/tracking
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/logs:/logs
    command: "mvn spring-boot:run"
    ports:
      - "8080"
      - "9090"
      - "5005"
