version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: tracking-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=tracking
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
  backend:
    container_name: backend-api
    depends_on:
      - db
      - rabbitmq
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
      - SPRING_PROFILE_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tracking-db:5432/tracking
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/logs:/logs
    command: "mvn spring-boot:run"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "5005:5005"
