[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run man
name = "main"
path = "src/main.rs"

[dependencies]
amqprs = "1.7.0"
tokio = { version = "1.0", features = ["full"] }
